name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --onefile --name="CXA" --add-data="*.py;." --windowed --icon="assets/icon.ico" main.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: CXA-Crypto-System-Windows
        path: dist/CXA.exe